# Generated by Django 4.0.7 on 2022-09-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('StudentName', models.CharField(max_length=100)),
                ('StudentRollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('StudentBranch', models.CharField(max_length=3)),
                ('StudentGPA', models.FloatField()),
                ('StudentSection', models.CharField(max_length=1)),
            ],
        ),
    ]
